Import Libraries and Load Dataset

In [1]:
import pandas as pd
import numpy as np
from IPython.display import display
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 120)
file_path = "Day10_Flight_Operations_Dataset.csv"
df = pd.read_csv(file_path)
print("Dataset loaded successfully")
print("Shape:", df.shape)

Dataset loaded successfully
Shape: (180, 17)

Understand the Dataset

In [2]:
display(df.head())
display(df.tail())
print("Columns:", df.columns.tolist())
print("Shape:", df.shape)
display(df.dtypes.to_frame("Data Type"))
df.info()

,Flight_ID,Flight_Date,Airline,Origin,Destination,Aircraft,Travel_Class,Passengers,Seat_Capacity,Average_Ticket_Price,Delay_Minutes,Flight_Status,Weather,Booking_Channel,Avg_Baggage_Kg,Meal_Preference,Passenger_Satisfaction
0,FL0001,2026-03-23,SpiceJet,Mumbai,Bengaluru,Airbus A319,Economy,210,180,6894,50.0,Delayed,Storm,Online Travel Portal,23,No Meal,3
1,FL0002,2026-06-07,Akasa Air,Delhi,Mumbai,Boeing 737,Economy,70,210,4468,0.0,On Time,Fog,Travel Agency,16,Vegan,5
2,FL0003,2026-05-12,Air India,Kochi,Delhi,Boeing 737,Economy,67,220,4713,5.0,On Time,Rain,Travel Agency,19,No Meal,2
3,FL0004,2026-05-30,Akasa Air,Srinagar,Delhi,Airbus A319,Economy,153,220,3791,35.0,Delayed,Storm,Travel Agency,18,No Meal,2
4,FL0005,2026-02-27,Air India,Pune,Delhi,Airbus A319,Premium Economy,178,180,6505,20.0,Delayed,Cloudy,Airline Website,25,No Meal,5

,Flight_ID,Flight_Date,Airline,Origin,Destination,Aircraft,Travel_Class,Passengers,Seat_Capacity,Average_Ticket_Price,Delay_Minutes,Flight_Status,Weather,Booking_Channel,Avg_Baggage_Kg,Meal_Preference,Passenger_Satisfaction
175,FL0176,2026-04-10,IndiGo,Ahmedabad,Bengaluru,Airbus A320,Economy,48,189,4298,0.0,On Time,Storm,Mobile App,11,Vegetarian,5
176,FL0177,2026-02-17,Vistara,Chennai,Mumbai,Airbus A320,Business,124,180,17306,20.0,Delayed,Cloudy,Mobile App,8,No Meal,5
177,FL0178,2026-04-30,IndiGo,Delhi,Mumbai,Airbus A319,Economy,112,186,4490,110.0,Delayed,Fog,Online Travel Portal,16,Vegetarian,3
178,FL0179,2026-05-08,Vistara,Bengaluru,Kochi,Airbus A320,Economy,134,189,5413,20.0,Delayed,Rain,Online Travel Portal,9,No Meal,2
179,FL0180,2026-01-22,Akasa Air,Delhi,Mumbai,Airbus A321,Economy,144,210,3767,75.0,Delayed,Fog,Online Travel Portal,17,No Meal,5

Columns: ['Flight_ID', 'Flight_Date', 'Airline', 'Origin', 'Destination', 'Aircraft', 'Travel_Class', 'Passengers', 'Seat_Capacity', 'Average_Ticket_Price', 'Delay_Minutes', 'Flight_Status', 'Weather', 'Booking_Channel', 'Avg_Baggage_Kg', 'Meal_Preference', 'Passenger_Satisfaction']
Shape: (180, 17)

                       Data Type
Flight_ID                    str
Flight_Date                  str
Airline                      str
Origin                       str
Destination                  str
Aircraft                     str
Travel_Class                 str
Passengers                 int64
Seat_Capacity              int64
Average_Ticket_Price       int64
Delay_Minutes            float64
Flight_Status                str
Weather                      str
Booking_Channel              str
Avg_Baggage_Kg             int64
Meal_Preference              str
Passenger_Satisfaction     int64

<class 'pandas.DataFrame'>
RangeIndex: 180 entries, 0 to 179
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Flight_ID               180 non-null    str
 1   Flight_Date             180 non-null    str
 2   Airline                 180 non-null    str
 3   Origin                  180 non-null    str
 4   Destination             180 non-null    str
 5   Aircraft                180 non-null    str
 6   Travel_Class            180 non-null    str
 7   Passengers              180 non-null    int64
 8   Seat_Capacity           180 non-null    int64
 9   Average_Ticket_Price    180 non-null    int64
 10  Delay_Minutes           173 non-null    float64
 11  Flight_Status           180 non-null    str
 12  Weather                 180 non-null    str
 13  Booking_Channel         180 non-null    str
 14  Avg_Baggage_Kg          180 non-null    int64
 15  Meal_Preference         180 non-null    str
 16  Passenger_Satisfaction  180 non-null    int64
dtypes: float64(1), int64(5), str(11)
memory usage: 40.4 KB

Data Quality Checks

In [3]:
print("Missing values:")
display(df.isnull().sum().sort_values(ascending=False).to_frame("Missing Values"))
print("Duplicate rows:", df.duplicated().sum())
print("Unique values:")
display(df.nunique().sort_values().to_frame("Unique Values"))

Missing values:

                        Missing Values
Delay_Minutes                        7
Flight_ID                            0
Flight_Date                          0
Origin                               0
Airline                              0
Aircraft                             0
Travel_Class                         0
Passengers                           0
Destination                          0
Seat_Capacity                        0
Average_Ticket_Price                 0
Flight_Status                        0
Weather                              0
Booking_Channel                      0
Avg_Baggage_Kg                       0
Meal_Preference                      0
Passenger_Satisfaction               0

Duplicate rows: 0
Unique values:

                        Unique Values
Travel_Class                        3
Flight_Status                       3
Booking_Channel                     4
Aircraft                            4
Meal_Preference                     4
Passenger_Satisfaction              4
Weather                             5
Seat_Capacity                       5
Airline                             6
Destination                         8
Delay_Minutes                       8
Origin                             11
Avg_Baggage_Kg                     21
Flight_Date                       111
Passengers                        115
Average_Ticket_Price              179
Flight_ID                         180

Descriptive Statistics

In [4]:
display(df.describe().T)
display(df.describe(include="all").T)

                        count         mean          std     min      25%     50%      75%      max
Passengers              180.0   122.772222    45.635651    45.0    78.75   125.0   162.25    210.0
Seat_Capacity           180.0   197.238889    15.408176   180.0   186.00   189.0   210.00    220.0
Average_Ticket_Price    180.0  6111.677778  3615.220040  1949.0  3815.50  5380.0  6790.00  27832.0
Delay_Minutes           173.0    19.335260    29.029712     0.0     0.00     5.0    20.00    110.0
Avg_Baggage_Kg          180.0    15.150000     5.705506     5.0    10.00    15.5    20.00     25.0
Passenger_Satisfaction  180.0     3.494444     1.169908     2.0     2.00     3.0     5.00      5.0

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Flight_ID,180,180,FL0001,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Flight_Date,180,111,2026-02-10,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Airline,180,6,Vistara,37,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Origin,180,11,Delhi,43,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Destination,180,8,Delhi,51,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Aircraft,180,4,Airbus A319,60,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Travel_Class,180,3,Economy,134,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Passengers,180.0,NaN,NaN,NaN,122.772222,45.635651,45.0,78.75,125.0,162.25,210.0
Seat_Capacity,180.0,NaN,NaN,NaN,197.238889,15.408176,180.0,186.0,189.0,210.0,220.0
Average_Ticket_Price,180.0,NaN,NaN,NaN,6111.677778,3615.22004,1949.0,3815.5,5380.0,6790.0,27832.0
Delay_Minutes,173.0,NaN,NaN,NaN,19.33526,29.029712,0.0,0.0,5.0,20.0,110.0
Flight_Status,180,3,On Time,114,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Weather,180,5,Rain,43,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Booking_Channel,180,4,Online Travel Portal,50,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Avg_Baggage_Kg,180.0,NaN,NaN,NaN,15.15,5.705506,5.0,10.0,15.5,20.0,25.0
Meal_Preference,180,4,Vegetarian,52,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Passenger_Satisfaction,180.0,NaN,NaN,NaN,3.494444,1.169908,2.0,2.0,3.0,5.0,5.0

Selecting Relevant Data

In [5]:
numeric_data = df.select_dtypes(include="number")
categorical_data = df.select_dtypes(exclude="number")
print("Numerical data:")
display(numeric_data.head())
print("Categorical data:")
display(categorical_data.head())

Numerical data:

   Passengers  Seat_Capacity  Average_Ticket_Price  Delay_Minutes  Avg_Baggage_Kg  Passenger_Satisfaction
0         210            180                  6894           50.0              23                       3
1          70            210                  4468            0.0              16                       5
2          67            220                  4713            5.0              19                       2
3         153            220                  3791           35.0              18                       2
4         178            180                  6505           20.0              25                       5

Categorical data:

,Flight_ID,Flight_Date,Airline,Origin,Destination,Aircraft,Travel_Class,Flight_Status,Weather,Booking_Channel,Meal_Preference
0,FL0001,2026-03-23,SpiceJet,Mumbai,Bengaluru,Airbus A319,Economy,Delayed,Storm,Online Travel Portal,No Meal
1,FL0002,2026-06-07,Akasa Air,Delhi,Mumbai,Boeing 737,Economy,On Time,Fog,Travel Agency,Vegan
2,FL0003,2026-05-12,Air India,Kochi,Delhi,Boeing 737,Economy,On Time,Rain,Travel Agency,No Meal
3,FL0004,2026-05-30,Akasa Air,Srinagar,Delhi,Airbus A319,Economy,Delayed,Storm,Travel Agency,No Meal
4,FL0005,2026-02-27,Air India,Pune,Delhi,Airbus A319,Premium Economy,Delayed,Cloudy,Airline Website,No Meal

Filtering Data

In [6]:
if len(numeric_data.columns):
    metric = numeric_data.columns[0]
    threshold = df[metric].median()
    filtered = df[df[metric] >= threshold]
    print(f"Records where {metric} >= median ({threshold:.2f}):")
    display(filtered.head(10))

Records where Passengers >= median (125.00):

,Flight_ID,Flight_Date,Airline,Origin,Destination,Aircraft,Travel_Class,Passengers,Seat_Capacity,Average_Ticket_Price,Delay_Minutes,Flight_Status,Weather,Booking_Channel,Avg_Baggage_Kg,Meal_Preference,Passenger_Satisfaction
0,FL0001,2026-03-23,SpiceJet,Mumbai,Bengaluru,Airbus A319,Economy,210,180,6894,50.0,Delayed,Storm,Online Travel Portal,23,No Meal,3
3,FL0004,2026-05-30,Akasa Air,Srinagar,Delhi,Airbus A319,Economy,153,220,3791,35.0,Delayed,Storm,Travel Agency,18,No Meal,2
4,FL0005,2026-02-27,Air India,Pune,Delhi,Airbus A319,Premium Economy,178,180,6505,20.0,Delayed,Cloudy,Airline Website,25,No Meal,5
6,FL0007,2026-06-17,Air India Express,Delhi,Srinagar,Airbus A319,Premium Economy,178,210,9430,0.0,On Time,Storm,Online Travel Portal,18,Vegetarian,4
7,FL0008,2026-04-28,Air India,Delhi,Chennai,Airbus A319,Business,157,220,14173,0.0,On Time,Fog,Airline Website,25,Vegan,5
9,FL0010,2026-06-12,Akasa Air,Ahmedabad,Bengaluru,Airbus A321,Economy,125,220,2500,12.0,On Time,Cloudy,Online Travel Portal,23,Non-Vegetarian,4
10,FL0011,2026-04-17,Air India,Mumbai,Bengaluru,Airbus A321,Economy,195,189,3393,5.0,On Time,Clear,Airline Website,17,Vegetarian,2
12,FL0013,2026-05-14,SpiceJet,Pune,Delhi,Airbus A319,Economy,162,220,4689,0.0,On Time,Cloudy,Mobile App,6,Vegetarian,5
14,FL0015,2026-01-21,Akasa Air,Lucknow,Delhi,Boeing 737,Economy,133,186,3911,0.0,On Time,Cloudy,Travel Agency,21,No Meal,5
19,FL0020,2026-02-01,SpiceJet,Mumbai,Kolkata,Airbus A320,Economy,125,210,5715,12.0,On Time,Fog,Travel Agency,24,Non-Vegetarian,5

Sorting Records

In [7]:
if len(numeric_data.columns):
    metric = numeric_data.columns[0]
    sorted_data = df.sort_values(metric, ascending=False)
    print(f"Top records sorted by {metric}:")
    display(sorted_data.head(10))

Top records sorted by Passengers:

,Flight_ID,Flight_Date,Airline,Origin,Destination,Aircraft,Travel_Class,Passengers,Seat_Capacity,Average_Ticket_Price,Delay_Minutes,Flight_Status,Weather,Booking_Channel,Avg_Baggage_Kg,Meal_Preference,Passenger_Satisfaction
0,FL0001,2026-03-23,SpiceJet,Mumbai,Bengaluru,Airbus A319,Economy,210,180,6894,50.0,Delayed,Storm,Online Travel Portal,23,No Meal,3
30,FL0031,2026-01-08,Vistara,Delhi,Srinagar,Airbus A321,Premium Economy,209,180,9962,50.0,Delayed,Cloudy,Mobile App,9,Vegetarian,4
92,FL0093,2026-04-30,Air India Express,Srinagar,Delhi,Airbus A319,Business,209,220,12970,0.0,On Time,Clear,Travel Agency,8,Vegan,2
148,FL0149,2026-02-10,Akasa Air,Jaipur,Mumbai,Airbus A319,Economy,202,210,6239,5.0,On Time,Rain,Online Travel Portal,8,No Meal,5
69,FL0070,2026-06-12,SpiceJet,Srinagar,Delhi,Boeing 737,Economy,201,189,2959,20.0,Delayed,Rain,Online Travel Portal,12,Vegan,4
153,FL0154,2026-04-09,Air India,Mumbai,Bengaluru,Airbus A321,Economy,201,186,3823,20.0,Delayed,Clear,Online Travel Portal,13,Vegan,2
29,FL0030,2026-04-10,SpiceJet,Delhi,Srinagar,Airbus A321,Economy,200,210,2716,75.0,Delayed,Storm,Airline Website,10,Vegan,3
94,FL0095,2026-06-14,Vistara,Bengaluru,Kochi,Airbus A319,Economy,199,189,4369,0.0,On Time,Fog,Online Travel Portal,11,Vegetarian,5
80,FL0081,2026-04-03,SpiceJet,Delhi,Mumbai,Airbus A320,Economy,199,180,2378,50.0,Delayed,Rain,Online Travel Portal,13,No Meal,4
107,FL0108,2026-05-30,IndiGo,Lucknow,Delhi,Airbus A319,Premium Economy,198,180,10551,75.0,Delayed,Rain,Travel Agency,13,Vegan,2

Grouping and Aggregation

In [8]:
group_col = 'Airline'
if group_col:
    print("Records by group:")
    display(df[group_col].value_counts().to_frame("Flight Count"))

    if len(numeric_data.columns):
        metric = numeric_data.columns[0]
        grouped = df.groupby(group_col)[metric].agg(["count","mean","min","max"])
        display(grouped.sort_values("mean", ascending=False))

Records by group:

                   Flight Count
Airline
Vistara                      37
SpiceJet                     32
IndiGo                       32
Akasa Air                    31
Air India                    24
Air India Express            24

                   count        mean  min  max
Airline
IndiGo                32  129.937500   48  198
Air India             24  128.083333   45  201
Air India Express     24  126.125000   57  209
SpiceJet              32  122.781250   49  210
Vistara               37  121.189189   45  209
Akasa Air             31  110.548387   50  202

Data Transformation

In [9]:
if len(numeric_data.columns):
    metric = numeric_data.columns[0]
    median_value = df[metric].median()
    df[f"{metric}_Level"] = df[metric].apply(
        lambda x: "High" if pd.notna(x) and x >= median_value else "Low"
    )
    display(df[[metric, f"{metric}_Level"]].head(10))

   Passengers Passengers_Level
0         210             High
1          70              Low
2          67              Low
3         153             High
4         178             High
5         123              Low
6         178             High
7         157             High
8          82              Low
9         125             High

Date/Time Analysis

In [10]:
date_columns = [c for c in df.columns if any(k in c.lower() for k in ["date", "time"])]
print("Detected date/time columns:", date_columns)
for c in date_columns:
    parsed = pd.to_datetime(df[c], errors="coerce")
    if parsed.notna().any():
        parsed_col = c + "_Parsed"
        df[parsed_col] = parsed
        print(f"Converted: {c}")
        display(df[[c, parsed_col]].head())

Detected date/time columns: ['Flight_Date']
Converted: Flight_Date

  Flight_Date Flight_Date_Parsed
0  2026-03-23         2026-03-23
1  2026-06-07         2026-06-07
2  2026-05-12         2026-05-12
3  2026-05-30         2026-05-30
4  2026-02-27         2026-02-27

In [11]:
airline_col = 'Airline'
status_col = 'Flight_Status'
origin_col = 'Origin'
dest_col = 'Destination'
delay_col = 'Delay_Minutes'
duration_col = None
distance_col = None
if airline_col:
    print("1. Which airline/carrier has the most flights?")
    display(df[airline_col].value_counts().head(10).to_frame("Flight Count"))
if status_col:
    print("2. What are the most common flight statuses?")
    display(df[status_col].value_counts().to_frame("Count"))
if origin_col:
    print("3. Which origins are busiest?")
    display(df[origin_col].value_counts().head(10).to_frame("Flight Count"))
if dest_col:
    print("4. Which destinations are busiest?")
    display(df[dest_col].value_counts().head(10).to_frame("Flight Count"))
for label, col in [("Delay", delay_col), ("Duration", duration_col), ("Distance", distance_col)]:
    if col:
        values = pd.to_numeric(df[col], errors="coerce")
        print(f"Highest recorded {label} values:")
        display(df.loc[values.nlargest(10).index, [col]])

1. Which airline/carrier has the most flights?

                   Flight Count
Airline
Vistara                      37
SpiceJet                     32
IndiGo                       32
Akasa Air                    31
Air India                    24
Air India Express            24

2. What are the most common flight statuses?

               Count
Flight_Status
On Time          114
Delayed           59
Cancelled          7

3. Which origins are busiest?

           Flight Count
Origin
Delhi                43
Mumbai               29
Bengaluru            21
Srinagar             15
Kochi                14
Ahmedabad            12
Pune                 11
Lucknow              11
Chennai               9
Jaipur                8

4. Which destinations are busiest?

             Flight Count
Destination
Delhi                  51
Mumbai                 30
Bengaluru              28
Kolkata                20
Chennai                17
Srinagar               13
Hyderabad              13
Kochi                   8

Highest recorded Delay values:

     Delay_Minutes
26           110.0
50           110.0
57           110.0
82           110.0
128          110.0
146          110.0
161          110.0
169          110.0
177          110.0
8             75.0

In [12]:
airline_col = 'Airline'
status_col = 'Flight_Status'
metric_col = 'Delay_Minutes'

if airline_col and status_col:
    print("Airline/carrier vs status:")
    display(pd.crosstab(df[airline_col], df[status_col]))
if airline_col and metric_col:
    comparison = (
        df.groupby(airline_col)[metric_col]
          .agg(["count","mean","median","min","max"])
          .sort_values("mean", ascending=False)
    )
    print("Metric statistics by airline/carrier:", metric_col)
    display(comparison)

Airline/carrier vs status:

Flight_Status      Cancelled  Delayed  On Time
Airline
Air India                  1        9       14
Air India Express          0        6       18
Akasa Air                  1        8       22
IndiGo                     0       11       21
SpiceJet                   3       12       17
Vistara                    2       13       22

Metric statistics by airline/carrier: Delay_Minutes

                   count       mean  median  min    max
Airline
IndiGo                32  25.031250     5.0  0.0  110.0
SpiceJet              29  24.137931    12.0  0.0  110.0
Air India             23  21.260870     5.0  0.0  110.0
Vistara               35  18.628571    12.0  0.0   75.0
Akasa Air             30  14.400000     5.0  0.0   75.0
Air India Express     24  11.291667     0.0  0.0  110.0

In [13]:
print("Final shape:", df.shape)
display(df.head())

Final shape: (180, 19)

,Flight_ID,Flight_Date,Airline,Origin,Destination,Aircraft,Travel_Class,Passengers,Seat_Capacity,Average_Ticket_Price,Delay_Minutes,Flight_Status,Weather,Booking_Channel,Avg_Baggage_Kg,Meal_Preference,Passenger_Satisfaction,Passengers_Level,Flight_Date_Parsed
0,FL0001,2026-03-23,SpiceJet,Mumbai,Bengaluru,Airbus A319,Economy,210,180,6894,50.0,Delayed,Storm,Online Travel Portal,23,No Meal,3,High,2026-03-23
1,FL0002,2026-06-07,Akasa Air,Delhi,Mumbai,Boeing 737,Economy,70,210,4468,0.0,On Time,Fog,Travel Agency,16,Vegan,5,Low,2026-06-07
2,FL0003,2026-05-12,Air India,Kochi,Delhi,Boeing 737,Economy,67,220,4713,5.0,On Time,Rain,Travel Agency,19,No Meal,2,Low,2026-05-12
3,FL0004,2026-05-30,Akasa Air,Srinagar,Delhi,Airbus A319,Economy,153,220,3791,35.0,Delayed,Storm,Travel Agency,18,No Meal,2,High,2026-05-30
4,FL0005,2026-02-27,Air India,Pune,Delhi,Airbus A319,Premium Economy,178,180,6505,20.0,Delayed,Cloudy,Airline Website,25,No Meal,5,High,2026-02-27

In [14]:
observations = []
observations.append(f"1. The dataset contains {len(df):,} flight records and {df.shape[1]} columns.")
if 'Airline':
    x = df['Airline'].value_counts()
    if len(x):
        observations.append(f"2. The most represented airline/carrier is {x.index[0]} with {x.iloc[0]:,} records.")
if 'Flight_Status':
    x = df['Flight_Status'].value_counts()
    if len(x):
        observations.append(f"3. The most common flight status is {x.index[0]} with {x.iloc[0]:,} records.")
if 'Delay_Minutes':
    x = pd.to_numeric(df['Delay_Minutes'], errors="coerce").dropna()
    if len(x):
        observations.append(f"4. The average recorded delay is {x.mean():.2f}, while the maximum is {x.max():.2f}.")
if 'Origin':
    x = df['Origin'].value_counts()
    if len(x):
        observations.append(f"5. The busiest origin/departure location is {x.index[0]} with {x.iloc[0]:,} flights.")
if 'Destination':
    x = df['Destination'].value_counts()
    if len(x):
        observations.append(f"6. The most frequent destination/arrival location is {x.index[0]} with {x.iloc[0]:,} flights.")
if None:
    x = pd.to_numeric(df[None], errors="coerce").dropna()
    if len(x):
        observations.append(f"7. The average flight duration is {x.mean():.2f} in the dataset's recorded unit.")
if None:
    x = pd.to_numeric(df[None], errors="coerce").dropna()
    if len(x):
        observations.append(f"8. The average flight distance is {x.mean():.2f} in the dataset's recorded unit.")
for observation in observations[:8]:
    print(observation)

1. The dataset contains 180 flight records and 19 columns.
2. The most represented airline/carrier is Vistara with 37 records.
3. The most common flight status is On Time with 114 records.
4. The average recorded delay is 19.34, while the maximum is 110.00.
5. The busiest origin/departure location is Delhi with 43 flights.
6. The most frequent destination/arrival location is Delhi with 51 flights.